/* eslint-disable */

//  API
export const SET_ACCESS_TOKEN = 'SET_ACCESS_TOKEN';
export const SET_TOP_PLAYERS = 'SET_TOP_PLAYERS';  //  If Rift Level is equal lower Rank win
export const SET_SEASON_HERO_CLASS = 'SET_SEASON_HERO_CLASS';
export const SET_SHARED_HEROES_CLASS_DATA = 'SET_SHARED_HEROES_CLASS_DATA';
export const SET_SEASONS_LEADERBOARDS_LIST = 'SET_SEASONS_LEADERBOARDS_LIST';
